spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  secret-key: going-trackton.going_project_2023_secret_key
  token:
    expired-time-ms: 2592000000

cloud:
  aws:
    credentials:
      access-key: AKIAUQ4BJWFQFK3WRZFY
      secret-key: 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
    s3:
      bucket: going-hackaton
    region:
      static: ap-northeast-2
    stack:
      auto: false

papago:
  client:
    id: 09j0gV6roAEn3UL1NKp9
    secret: qeXAp0srHw

naver:
  client:
    id: fYGQS21hC2R50RVBcuVe
    secret: XOv7tUVyq7

openai:
  api:
    key: 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

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/going
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://going.c5l0tfogmvlj.ap-northeast-2.rds.amazonaws.com:3306/going?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      #            ddl-auto: create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true